# coding: utf-8

"""
    国税庁API

    国税庁が提供するインボイス制度適格請求書発行事業者公表システムWeb-APIを使用するためのクライアントAPI(https://www.invoice-kohyo.nta.go.jp/web-api/index.html)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Announcement(BaseModel):
    """
    Announcement
    """ # noqa: E501
    sequence_number: Annotated[str, Field(min_length=1, strict=True, max_length=8)] = Field(description="一連番号", alias="sequenceNumber")
    registrated_number: StrictStr = Field(description="登録番号", alias="registratedNumber")
    process: StrictStr = Field(description="事業者処理区分")
    correct: StrictStr = Field(description="訂正区分")
    kind: StrictStr = Field(description="人格区分")
    country: StrictStr = Field(description="国内外区分")
    latest: StrictStr = Field(description="最新履歴")
    registration_date: date = Field(description="登録年月日", alias="registrationDate")
    update_date: date = Field(description="更新年月日", alias="updateDate")
    disposal_date: StrictStr = Field(description="取消年月日", alias="disposalDate")
    expire_date: StrictStr = Field(description="失効年月日", alias="expireDate")
    address: Annotated[str, Field(strict=True, max_length=600)] = Field(description="本店又は主たる事務所の所在地（法人）")
    address_prefecture_code: StrictStr = Field(description="本店又は主たる事務所の所在地都道府県コード（法人）", alias="addressPrefectureCode")
    address_city_code: StrictStr = Field(description="本店又は主たる事務所の所在地市区町村コード（法人）", alias="addressCityCode")
    address_request: Annotated[str, Field(strict=True, max_length=600)] = Field(description="本店又は主たる事務所の所在地（公表申出）", alias="addressRequest")
    address_request_prefecture_code: StrictStr = Field(description="本店又は主たる事務所の所在地都道府県コード（公表申出）", alias="addressRequestPrefectureCode")
    address_request_city_code: StrictStr = Field(description="本店又は主たる事務所の所在地市区町村コード（公表申出）", alias="addressRequestCityCode")
    kana: Annotated[str, Field(strict=True, max_length=500)] = Field(description="日本語（カナ）")
    name: Annotated[str, Field(strict=True, max_length=300)] = Field(description="氏名又は名称")
    address_inside: Annotated[str, Field(strict=True, max_length=300)] = Field(description="国内において行う資産の譲渡等に係る事務所、事業所その他これらに準ずるものの所在地", alias="addressInside")
    address_inside_prefecture_code: Optional[StrictStr] = Field(default=None, description="国内において行う資産の譲渡等に係る事務所、事業所その他これらに準ずるものの所在地都道府県コード", alias="addressInsidePrefectureCode")
    address_inside_city_code: StrictStr = Field(description="国内において行う資産の譲渡等に係る事務所、事業所その他これらに準ずるものの所在地市区町村コード", alias="addressInsideCityCode")
    trade_name: Annotated[str, Field(strict=True, max_length=200)] = Field(description="主たる屋号", alias="tradeName")
    popular_name_previous_name: Annotated[str, Field(strict=True, max_length=200)] = Field(description="通称・旧姓", alias="popularName_previousName")
    __properties: ClassVar[List[str]] = ["sequenceNumber", "registratedNumber", "process", "correct", "kind", "country", "latest", "registrationDate", "updateDate", "disposalDate", "expireDate", "address", "addressPrefectureCode", "addressCityCode", "addressRequest", "addressRequestPrefectureCode", "addressRequestCityCode", "kana", "name", "addressInside", "addressInsidePrefectureCode", "addressInsideCityCode", "tradeName", "popularName_previousName"]

    @field_validator('process')
    def process_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['01', '02', '03', '04', '99']):
            raise ValueError("must be one of enum values ('01', '02', '03', '04', '99')")
        return value

    @field_validator('correct')
    def correct_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['0', '1', '']):
            raise ValueError("must be one of enum values ('0', '1', '')")
        return value

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['1', '2']):
            raise ValueError("must be one of enum values ('1', '2')")
        return value

    @field_validator('country')
    def country_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['1', '2', '3']):
            raise ValueError("must be one of enum values ('1', '2', '3')")
        return value

    @field_validator('latest')
    def latest_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['0', '1']):
            raise ValueError("must be one of enum values ('0', '1')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Announcement from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Announcement from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sequenceNumber": obj.get("sequenceNumber"),
            "registratedNumber": obj.get("registratedNumber"),
            "process": obj.get("process"),
            "correct": obj.get("correct"),
            "kind": obj.get("kind"),
            "country": obj.get("country"),
            "latest": obj.get("latest"),
            "registrationDate": obj.get("registrationDate"),
            "updateDate": obj.get("updateDate"),
            "disposalDate": obj.get("disposalDate"),
            "expireDate": obj.get("expireDate"),
            "address": obj.get("address"),
            "addressPrefectureCode": obj.get("addressPrefectureCode"),
            "addressCityCode": obj.get("addressCityCode"),
            "addressRequest": obj.get("addressRequest"),
            "addressRequestPrefectureCode": obj.get("addressRequestPrefectureCode"),
            "addressRequestCityCode": obj.get("addressRequestCityCode"),
            "kana": obj.get("kana"),
            "name": obj.get("name"),
            "addressInside": obj.get("addressInside"),
            "addressInsidePrefectureCode": obj.get("addressInsidePrefectureCode"),
            "addressInsideCityCode": obj.get("addressInsideCityCode"),
            "tradeName": obj.get("tradeName"),
            "popularName_previousName": obj.get("popularName_previousName")
        })
        return _obj


