# coding: utf-8

"""
    国税庁API

    国税庁が提供するインボイス制度適格請求書発行事業者公表システムWeb-APIを使用するためのクライアントAPI(https://www.invoice-kohyo.nta.go.jp/web-api/index.html)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from kendama.models.announcement import Announcement
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResponseBody(BaseModel):
    """
    ResponseBody
    """ # noqa: E501
    last_update_date: Optional[date] = Field(default=None, description="最終更新年月日", alias="lastUpdateDate")
    count: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=8)]] = Field(default=None, description="総件数")
    divide_number: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=6)]] = Field(default=None, description="分割番号", alias="divideNumber")
    divide_size: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=6)]] = Field(default=None, description="分割数", alias="divideSize")
    announcement: Optional[List[Announcement]] = None
    __properties: ClassVar[List[str]] = ["lastUpdateDate", "count", "divideNumber", "divideSize", "announcement"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResponseBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in announcement (list)
        _items = []
        if self.announcement:
            for _item_announcement in self.announcement:
                if _item_announcement:
                    _items.append(_item_announcement.to_dict())
            _dict['announcement'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResponseBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "lastUpdateDate": obj.get("lastUpdateDate"),
            "count": obj.get("count"),
            "divideNumber": obj.get("divideNumber"),
            "divideSize": obj.get("divideSize"),
            "announcement": [Announcement.from_dict(_item) for _item in obj["announcement"]] if obj.get("announcement") is not None else None
        })
        return _obj


